/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';


export interface ContentTenantUpdateDto { 
    entityType?: string;
    entityId?: ApiCoursesIdGetIdParameter;
    newTenantId?: string;
}

