/**
 * BifrostLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';
import { CourseTenant } from './courseTenant';
import { Lesson } from './lesson';


export interface Course { 
    title?: string;
    description?: string | null;
    imageUrl?: string | null;
    isApproved?: boolean;
    lessons?: Array<Lesson>;
    sharedWithTenants?: Array<CourseTenant>;
    id?: ApiCoursesIdGetIdParameter;
    tenantId?: string | null;
    createdAt?: string;
    updatedAt?: string | null;
}

