/**
 * WellaLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';


export interface CreateLessonDto { 
    title: string;
    content: string | null;
    courseId: ApiCoursesIdGetIdParameter;
    videoUrl?: string | null;
    pdfUrl?: string | null;
    externalVideoUrl?: string | null;
}

