/**
 * WellaLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';


export interface Lesson { 
    title?: string;
    content?: string | null;
    videoUrl?: string | null;
    pdfUrl?: string | null;
    externalVideoUrl?: string | null;
    courseId?: ApiCoursesIdGetIdParameter;
    id?: ApiCoursesIdGetIdParameter;
    tenantId?: string | null;
    createdAt?: string;
    updatedAt?: string | null;
}

