/**
 * WellaLms.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiCoursesIdGetIdParameter } from './apiCoursesIdGetIdParameter';


export interface LessonProgressDto { 
    lessonId?: ApiCoursesIdGetIdParameter;
    lessonTitle?: string;
    content?: string | null;
    videoUrl?: string | null;
    pdfUrl?: string | null;
    externalVideoUrl?: string | null;
    isCompleted?: boolean;
    completedAt?: string | null;
}

